version: '3'
services:
    hhvm:
        build:
            context: .
        ports:
            - 80:80
        volumes:
            - ./:/app
            - composer_packages:/app/vendor

volumes:
    composer_packages: